---
  - name: Install Obligatorio software
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - name: Create virtualhost content directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      mode: '0755'
    loop:
      - /var/www/"{{ sitio }}"
      - /var/www/"{{ sitio }}"/html
      - /var/www/"{{ sitio }}"/cgi-bin

  - name: Load apache modules for proxy in Ubuntu
    apache2_module:
      name: proxy
      state: present
    notify: Restart apache2
  
  - name: Create virtualhost configuration
    template:
      src: ./templates/apache2.j2
      dest: /etc/apache2/sites-enabled/000-default.conf
      owner: root
      mode: '0644'
    notify: Restart apache2

  - name: Start and enable apache
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop: 
       - httpd
       - mariadb-server

  - name: Configure firewall
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
       - http
       - mysql
